import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Linking, Platform, ScrollView, Share, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Location from 'expo-location';
import * as Clipboard from 'expo-clipboard';
import { useLocalSearchParams, useRouter } from 'expo-router';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { useThemeColors } from '@/styles/commonStyles';
import { generateMidpointPlaces } from '@/utils/sessionUtils';
import { getSecureSession, saveSecurePlaces, setReceiverLocation, setSecureSessionStatus } from '@/utils/sessionApi';

interface SessionPlace { id?: string; session_id: string; place_id: string; name: string; address: string; lat: number; lng: number; rank: number; }
interface MeetSession { id:string; type:string; sender_lat:number; sender_lng:number; receiver_lat:number|null; receiver_lng:number|null; status:string; join_code?:string; expires_at:string; proposed_place_id:string|null; confirmed_place_id:string|null; }
const LABELS:Record<string,string>={coffee:'☕ Coffee',food:'🍔 Food',marketplace:'🛍️ Marketplace',gas:'⛽ Gas Station',park:'🌳 Park',police:'🚔 Police Station'};
const STATUS:Record<string,string>={waiting_for_receiver:'Waiting for other person...',connected:'Both locations found — finding midpoint...',proposed:'Place proposed — waiting for response',confirmed:'Meeting confirmed!',expired:'Session expired',no_places_found:'No places found near the midpoint'};

export default function SessionScreen(){
 const router=useRouter(); const params=useLocalSearchParams(); const colors=useThemeColors();
 const sessionId=Array.isArray(params.sessionId)?params.sessionId[0]:params.sessionId; const token=Array.isArray(params.token)?params.token[0]:params.token; const isSender=(Array.isArray(params.isSender)?params.isSender[0]:params.isSender)==='true';
 const [session,setSession]=useState<MeetSession|null>(null); const [places,setPlaces]=useState<SessionPlace[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const generating=useRef(false); const captureStarted=useRef(false);
 const refresh=async(show=false)=>{if(!sessionId||!token){setError('Invalid session link.');setLoading(false);return;}try{if(show)setLoading(true);const r=await getSecureSession(sessionId,token);const s=r.session as MeetSession;setSession(s);setPlaces(r.places||[]);setError(null);if(isSender&&s.receiver_lat!=null&&s.receiver_lng!=null&&(r.places||[]).length===0&&!generating.current)await generatePlaces(s);if(!isSender&&s.receiver_lat==null&&!captureStarted.current){captureStarted.current=true;setTimeout(captureReceiver,350);}}catch(e:any){if(show)setError(e?.message||'Failed to load session');}finally{if(show)setLoading(false);}};
 useEffect(()=>{refresh(true);},[sessionId,token]); useEffect(()=>{if(!sessionId||!token)return;const t=setInterval(()=>refresh(false),2000);return()=>clearInterval(t);},[sessionId,token,isSender]);
 const captureReceiver=async()=>{if(!sessionId||!token)return;try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted'){captureStarted.current=false;Alert.alert('Location Required','Please enable location access so MidPoint can find a meeting point.',[{text:'Cancel',style:'cancel'},{text:'Open Settings',onPress:()=>Linking.openSettings()}]);return;}const l=await Location.getCurrentPositionAsync({});await setReceiverLocation(sessionId,token,l.coords.latitude,l.coords.longitude);await refresh();}catch{captureStarted.current=false;Alert.alert('Error','Failed to capture location');}};
 const generatePlaces=async(s:MeetSession)=>{if(!sessionId||!token||s.receiver_lat==null||s.receiver_lng==null)return;generating.current=true;try{const f=await generateMidpointPlaces(s.sender_lat,s.sender_lng,s.receiver_lat,s.receiver_lng,s.type);if(!f.length){await setSecureSessionStatus(sessionId,token,'no_places_found');return;}const rows=f.slice(0,3).map((p,i)=>({session_id:sessionId,place_id:p.placeId||p.id||`place_${i}`,name:p.name,address:p.address||'',lat:p.latitude,lng:p.longitude,rank:i+1}));await saveSecurePlaces(sessionId,token,rows);await refresh();}catch{generating.current=false;}};
 const propose=async(p:SessionPlace)=>{if(!sessionId||!token)return;try{await setSecureSessionStatus(sessionId,token,'proposed',{placeId:p.place_id});await refresh();Alert.alert('Success',`Proposed: ${p.name}`);}catch{Alert.alert('Error','Failed to propose place');}}; const agree=async()=>{if(!sessionId||!token)return;try{await setSecureSessionStatus(sessionId,token,'confirmed');await refresh();Alert.alert('Confirmed!','Meeting place confirmed');}catch{Alert.alert('Error','Failed to confirm place');}}; const deny=async()=>{if(!sessionId||!token)return;try{await setSecureSessionStatus(sessionId,token,'connected',{clearProposal:true});await refresh();}catch{Alert.alert('Error','Failed to deny proposal');}};
 const directions=(p:SessionPlace)=>{const u=Platform.select({ios:`maps://app?daddr=${p.lat},${p.lng}`,android:`google.navigation:q=${p.lat},${p.lng}`,default:`https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lng}`});if(u)Linking.openURL(u);}; const share=async()=>{if(!session||!token)return;const u=`https://kjlbcgjvruyrqvkdtljz.supabase.co/functions/v1/join?sessionId=${encodeURIComponent(session.id)}&token=${encodeURIComponent(token)}`;const m=`Join me on MidPoint Meet! 📍\n\n${u}\n\nOr enter code: ${session.join_code||''}`;if(Platform.OS==='web'){await Clipboard.setStringAsync(m);Alert.alert('Copied!','Invite copied to clipboard.');}else await Share.share({message:m});};
 if(loading)return <SafeAreaView style={[styles.center,{backgroundColor:colors.background}]}><ActivityIndicator size="large" color={colors.primary}/><Text style={{color:colors.textSecondary,marginTop:12}}>Loading session...</Text></SafeAreaView>;
 if(error||!session)return <SafeAreaView style={[styles.center,{backgroundColor:colors.background}]}><MaterialIcons name="error-outline" size={60} color={colors.error}/><Text style={[styles.title,{color:colors.text}]}>Session Error</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{error||'Session unavailable'}</Text><TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary}]} onPress={()=>router.push('/(tabs)/(home)/')}><Text style={styles.primaryText}>Go Home</Text></TouchableOpacity></SafeAreaView>;
 const proposed=places.find(p=>p.place_id===session.proposed_place_id);const confirmed=places.find(p=>p.place_id===session.confirmed_place_id);
 return <SafeAreaView style={[styles.safe,{backgroundColor:colors.background}]}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><TouchableOpacity onPress={()=>router.back()}><MaterialIcons name="arrow-back" size={26} color={colors.text}/></TouchableOpacity><View style={{flex:1,marginLeft:14}}><Text style={[styles.title,{color:colors.text}]}>{LABELS[session.type]||session.type} Meetup</Text><Text style={{color:colors.textSecondary}}>{STATUS[session.status]||session.status}</Text></View></View>
 {session.status==='waiting_for_receiver'&&<View style={[styles.card,{backgroundColor:colors.card}]}><ActivityIndicator color={colors.primary}/><Text style={[styles.cardTitle,{color:colors.text}]}>Waiting for other person...</Text>{isSender&&<><Text style={[styles.code,{color:colors.text}]}>{session.join_code}</Text><TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary}]} onPress={share}><Text style={styles.primaryText}>Share Invite</Text></TouchableOpacity></>}</View>}
 {session.status==='connected'&&places.length===0&&<View style={[styles.card,{backgroundColor:colors.card}]}><ActivityIndicator color={colors.primary}/><Text style={[styles.body,{color:colors.textSecondary}]}>Finding the best midpoint options...</Text></View>}
 {session.status==='no_places_found'&&<View style={[styles.card,{backgroundColor:colors.card}]}><Text style={[styles.cardTitle,{color:colors.text}]}>No nearby places found</Text></View>}
 {places.length>0&&session.status!=='confirmed'&&<><Text style={[styles.section,{color:colors.text}]}>Meeting options</Text>{places.map(p=><View key={p.place_id} style={[styles.card,{backgroundColor:colors.card}]}><Text style={[styles.cardTitle,{color:colors.text}]}>{p.name}</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{p.address}</Text>{session.status==='proposed'&&session.proposed_place_id===p.place_id?<View style={styles.row}>{!isSender&&<TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary,flex:1}]} onPress={agree}><Text style={styles.primaryText}>Agree</Text></TouchableOpacity>}<TouchableOpacity style={[styles.secondary,{borderColor:colors.border,flex:1}]} onPress={deny}><Text style={{color:colors.text}}>Choose another</Text></TouchableOpacity></View>:session.status!=='proposed'&&<TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary}]} onPress={()=>propose(p)}><Text style={styles.primaryText}>Choose this place</Text></TouchableOpacity>}</View>)}</>}
 {session.status==='proposed'&&proposed&&<Text style={[styles.body,{color:colors.textSecondary}]}>Proposed: {proposed.name}</Text>}{session.status==='confirmed'&&confirmed&&<View style={[styles.card,{backgroundColor:colors.card}]}><MaterialIcons name="check-circle" size={48} color={colors.primary}/><Text style={[styles.cardTitle,{color:colors.text}]}>Meeting confirmed</Text><Text style={[styles.body,{color:colors.textSecondary}]}>{confirmed.name}{'\n'}{confirmed.address}</Text><TouchableOpacity style={[styles.primary,{backgroundColor:colors.primary}]} onPress={()=>directions(confirmed)}><Text style={styles.primaryText}>Get Directions</Text></TouchableOpacity></View>}</ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center',padding:24},content:{padding:20,paddingBottom:50},header:{flexDirection:'row',alignItems:'center',marginBottom:22},title:{fontSize:24,fontWeight:'700'},section:{fontSize:20,fontWeight:'700',marginBottom:10},card:{padding:18,borderRadius:16,marginBottom:14},cardTitle:{fontSize:19,fontWeight:'700',marginVertical:8},body:{fontSize:15,lineHeight:22,textAlign:'center'},code:{fontSize:30,fontWeight:'800',letterSpacing:5,textAlign:'center',marginVertical:16},primary:{paddingVertical:14,paddingHorizontal:18,borderRadius:12,alignItems:'center',marginTop:12},primaryText:{color:'#fff',fontWeight:'700'},secondary:{paddingVertical:14,paddingHorizontal:18,borderRadius:12,alignItems:'center',marginTop:12,borderWidth:1},row:{flexDirection:'row',gap:10}});
